set-window-option -g mode-keys vi
# set -g default-terminal "screen-256color"
set-option -g status-bg colour242
set-option -g pane-active-border-fg colour242
unbind C-b
set -g prefix `
bind ` send-pref
#switch panels
bind k select-pane -U # switch to panel Up
bind j select-pane -D # switch to panel Down 
bind h select-pane -L # switch to panel Left
bind l select-pane -R # switch to panel Right
unbind %
unbind s
unbind Up
unbind Down
unbind Left
unbind Right
bind s split-window -h
bind v split-window -v
bind -r Up resize-pane -U 8 
bind -r Down resize-pane -D 8 
bind -r Left resize-pane -L 15
bind -r Right resize-pane -R 15
